version: '3.4'

services:

  battleshipgameservice:
        container_name: "battleshipGameService"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "8000:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/